
import { Niche, Affiliate, Lead, LeadStatus } from './types';

export const COLORS = {
  primary: '#EAB308', // Caution Yellow
  background: '#0a0a0a',
  surface: '#171717',
  text: '#ffffff',
};

export const MOCK_AFFILIATES: Affiliate[] = [
  {
    id: 'admin-theboss',
    name: 'The Boss (Executive)',
    slug: 'the-boss',
    email: 'theboss@theinsuranceboss.com',
    username: 'theboss',
    password: 'adminboss',
    role: 'admin',
    niche: Niche.GENERAL,
    referralCode: 'BOSS-THE-BOSS',
    lifetimeEarnings: 0,
    monthlyResiduals: 0
  },
  {
    id: 'admin-bossadmin',
    name: 'Executive Admin',
    slug: 'boss-admin',
    email: 'admin@theinsuranceboss.com',
    username: 'bossadmin',
    password: 'admin',
    role: 'admin',
    niche: Niche.GENERAL,
    referralCode: 'BOSS-EXECUTIVE-ADMIN',
    lifetimeEarnings: 0,
    monthlyResiduals: 0
  },
  {
    id: 'aff-test-member',
    name: 'Test Inner Circle Member',
    slug: 'test-member',
    email: 'test@theinsuranceboss.com',
    username: 'innercirclemember',
    password: 'admin',
    role: 'partner',
    niche: Niche.GENERAL,
    referralCode: 'BOSS-TEST',
    businessName: 'Test Agency',
    industry: 'Business Services',
    lifetimeEarnings: 1200.00,
    monthlyResiduals: 150.00
  },
  {
    id: 'aff-chris',
    name: 'Chris Uccio',
    slug: 'chris-uccio',
    email: 'chris@theinsuranceboss.com',
    username: 'chrisuccio',
    password: 'christheinsuranceboss',
    role: 'partner',
    niche: Niche.GENERAL,
    referralCode: 'BOSS-CHRIS',
    businessName: 'Inner Circle Elite',
    industry: 'Executive Networking',
    lifetimeEarnings: 5000.00,
    monthlyResiduals: 500.00
  },
  {
    id: 'admin-chris',
    name: 'Chris Uccio (Admin)',
    slug: 'chris-uccio-admin',
    email: 'admin-chris@theinsuranceboss.com',
    username: 'chrisuccioadmin',
    password: 'admintheinsuranceboss',
    role: 'admin',
    niche: Niche.GENERAL,
    referralCode: 'BOSS-EXEC-CHRIS',
    lifetimeEarnings: 0,
    monthlyResiduals: 0
  },
  {
    id: 'aff-1',
    name: 'Romeo Escalante',
    slug: 'romeo-escalante',
    email: 'romeo@boss.com',
    username: 'Romeo',
    password: 'admin',
    role: 'partner',
    niche: Niche.GENERAL,
    referralCode: 'BOSS-ROMEO',
    businessName: 'Escalante Logistics',
    industry: 'Trucking',
    lifetimeEarnings: 4250.00,
    monthlyResiduals: 425.00
  },
  {
    id: 'aff-romeo-new',
    name: 'Romeo Member',
    slug: 'romeo-member',
    email: 'romeo@example.com',
    username: 'romeo@example.com',
    password: 'password123',
    role: 'partner',
    niche: Niche.GENERAL,
    referralCode: 'BOSS-ROMEO-MEMBER',
    lifetimeEarnings: 0,
    monthlyResiduals: 0
  },
  {
    id: 'admin-theinsuranceboss',
    name: 'The Insurance Boss',
    slug: 'the-insurance-boss',
    email: 'admin@theinsuranceboss.com',
    username: 'theinsuranceboss',
    password: 'adminboss',
    role: 'admin',
    niche: Niche.GENERAL,
    referralCode: 'BOSS-THE-INSURANCE-BOSS',
    lifetimeEarnings: 0,
    monthlyResiduals: 0
  }
];

export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-1',
    affiliateId: 'aff-chris',
    name: 'Alice Cooper',
    email: 'alice@example.com',
    phone: '555-0101',
    status: LeadStatus.CLOSED,
    productType: 'Commercial Auto',
    commissionEarned: 450.00,
    renewalDate: '2025-05-20',
    createdAt: '2024-05-20T10:00:00Z',
  },
  {
    id: 'lead-2',
    affiliateId: 'aff-1',
    name: 'Bob Marley',
    email: 'bob@example.com',
    phone: '555-0102',
    status: LeadStatus.QUOTED,
    productType: 'General Liability',
    commissionEarned: 0,
    createdAt: '2024-05-19T14:30:00Z',
  },
  {
    id: 'lead-test-1',
    affiliateId: 'aff-test-member',
    name: 'John Smith',
    email: 'john@example.com',
    phone: '(555) 123-4567',
    status: LeadStatus.RECEIVED,
    productType: 'Commercial Auto',
    commissionEarned: 0,
    createdAt: '2026-03-06T10:00:00Z',
  },
  {
    id: 'lead-test-2',
    affiliateId: 'aff-test-member',
    name: 'Jane Doe',
    email: 'jane@example.com',
    phone: '(555) 234-5678',
    status: LeadStatus.QUOTED,
    productType: 'General Liability',
    commissionEarned: 0,
    createdAt: '2026-03-06T11:00:00Z',
  },
  {
    id: 'lead-test-3',
    affiliateId: 'aff-test-member',
    name: 'Bob Johnson',
    email: 'bob@example.com',
    phone: '(555) 345-6789',
    status: LeadStatus.CLOSED,
    productType: 'Workers Comp',
    commissionEarned: 0,
    createdAt: '2026-03-06T12:00:00Z',
  },
  {
    id: 'lead-romeo-1',
    affiliateId: 'aff-romeo-new',
    name: 'Logistics Pro Inc',
    email: 'contact@logistics-pro.com',
    phone: '(555) 999-8888',
    status: LeadStatus.RECEIVED,
    productType: 'Trucking Liability',
    commissionEarned: 0,
    createdAt: '2026-03-07T09:00:00Z',
  },
  {
    id: 'lead-romeo-2',
    affiliateId: 'aff-romeo-new',
    name: 'Elite Construction',
    email: 'info@elite-build.com',
    phone: '(555) 777-6666',
    status: LeadStatus.QUOTED,
    productType: 'General Liability',
    commissionEarned: 0,
    createdAt: '2026-03-07T10:30:00Z',
  }
];
